### ISSUE TITLE
Postprocessing of MGX2 Conveyor-based jobs fails

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/dispatcher#12]
```
  org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "attributecount_attr_id_key"
  Detail: Key (attr_id)=(410939) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
        at de.cebitec.mgx.dispatcher.mgx.MGX2ConveyorJob.finished(MGX2ConveyorJob.java:380)
        at de.cebitec.mgx.dispatcher.mgx.MGX2ConveyorJob.process(MGX2ConveyorJob.java:97)
        at de.cebitec.mgx.dispatcher.api.JobI.run(JobI.java:64)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
]]

```

**Comment by sjaenick** [comment]
creation of summary attributecounts fails, but job is set to finished nonetheless

**Comment by sjaenick** [comment]
wrongly placed unique constraint on `attr_id` of the `attributecounts` table, should have been a unique constraint on `(attr_id, run_id)` instead.
